function [ desiredOutput, redPoints, blackPoints ] = separateDataMLPEKF( groupName )
%SEPARATEDATAMLPEKF Separates generated data based on the group name.
%   [DESIREDOUTPUT, REDPOINTS, BLACKPOINTS] =
%   SEPARATEDATAMLPEKF(GROUPNAMES) separates the data in GROUPNAMES into
%   two groups of red or black. GROUPNAMES is the vector generated by
%   genTrainingDataMLPEKF.
%
%   DESIREDOUTPUT is a vector containing the desired output of the MLP
%   network, 0.7 for red and -0.7 for black. REDPOINTS and BLACKPOINTS are
%   logical vectors containing ones where an element corresponds to the
%   group.
%
%   See also GENTRAININGDATAMLPEKF

% Differentiate the two groups
redPoints = ismember(groupName,'red');
blackPoints = ismember(groupName,'black');

% Generate the desired output
% Make red = 0.7 and black = -0.7
desiredValue = 1;
desiredOutput = redPoints*desiredValue + blackPoints*-desiredValue;

end

