numPoints = 5000;

[training, group] = genTrainingData(numPoints);

figure;
scatter(training(:,1),...
    training(:,2),...
    20,group,...
    'DisplayName','point(1:numPoints,1:2)(:,1) vs. point(1:numPoints,1:2)(:,2)',...
    'YDataSource','point(1:numPoints,1:2)(:,2)');
axis square