%% Batch analysis script
% Script for analyzing the data files generated by the batch simulation
% script

close all;

%% Find the files
defaultDirectory = 'C:\Users\Phil\Documents\School\Masters\ECE 739 - Neural Networks\Project\EKF MLP\BatchSimulation_20110817_173848';
directoryName = defaultDirectory;

% Allocate memory for all the data
%simulations = cell(2,1);

% Load the data files
% temp = load([directoryName filesep 'mlpekf_simulation20110818_00141.mat']);
temp = load([directoryName filesep 'mlpekf_simulation20110817_00098.mat']);
simulations = temp.simObj;

epochAxis = 1:1:simulations.NumEpochs;
figure;
plot(epochAxis,100*(1-simulations.Performance));
ylim([0 60]);
title('Performance of EKF-trained MLP');
xlabel('Epochs');
ylabel('Error Rate (%)');